name: "test-markdown"
description: "Generate markdown from test metadata"
author: "kirinnee"
inputs:
  current:
    required: true
    description: "current commit's validated data"
  history:
    required: true
    description: "historical (PR)'s commit's validated data"
outputs:
  currentMarkdown:
    description: renders markdown for current
  historyMarkdown:
    description: renders markdown for history
runs:
  using: "node16"
  main: "dist/index.js"
